# Generated by Django 3.2.15 on 2024-06-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_time', models.DateTimeField()),
                ('exercisetime', models.IntegerField()),
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'exercise',
                'managed': False,
            },
        ),
    ]
